// <auto-generated />
using System;
using CasgemMicroservice.Services.Cargo.DataAccesLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasgemMicroservice.Services.Cargo.DataAccesLayer.Migrations
{
    [DbContext(typeof(CargoContext))]
    [Migration("20230814151714_mig_1")]
    partial class mig_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CasgemMicroServices.Services.Cargo.EntityLayer.Entities.CargoDetail", b =>
                {
                    b.Property<int>("CargoDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoDetailID"), 1L, 1);

                    b.Property<int>("CargoStateID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.HasKey("CargoDetailID");

                    b.HasIndex("CargoStateID");

                    b.ToTable("CargoDetailes");
                });

            modelBuilder.Entity("CasgemMicroServices.Services.Cargo.EntityLayer.Entities.CargoState", b =>
                {
                    b.Property<int>("CargoStateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoStateID"), 1L, 1);

                    b.Property<int?>("CargoStateID1")
                        .HasColumnType("int");

                    b.HasKey("CargoStateID");

                    b.HasIndex("CargoStateID1");

                    b.ToTable("CargoStates");
                });

            modelBuilder.Entity("CasgemMicroServices.Services.Cargo.EntityLayer.Entities.CargoDetail", b =>
                {
                    b.HasOne("CasgemMicroServices.Services.Cargo.EntityLayer.Entities.CargoState", "CargoState")
                        .WithMany()
                        .HasForeignKey("CargoStateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoState");
                });

            modelBuilder.Entity("CasgemMicroServices.Services.Cargo.EntityLayer.Entities.CargoState", b =>
                {
                    b.HasOne("CasgemMicroServices.Services.Cargo.EntityLayer.Entities.CargoState", null)
                        .WithMany("CargoDetails")
                        .HasForeignKey("CargoStateID1");
                });

            modelBuilder.Entity("CasgemMicroServices.Services.Cargo.EntityLayer.Entities.CargoState", b =>
                {
                    b.Navigation("CargoDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
